spring.application.name=catalog-service

spring.config.import=optional:file:.env[.properties]

# Backend Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.data.web.pageable.max-page-size=50

spring.mvc.problem-details.enabled=true

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Cache Configuration
app.cache.redis.menu-ttl-minutes=${REDIS_MENU_TTL_MINUTES:5}
app.cache.redis.locations-ttl-hours=${REDIS_LOCATIONS_TTL_HOURS:24}

# Port
server.port=${PORT:8081}

